[tools]
chezmoi = "latest"
watchexec = "latest"

[tasks.dev]
run = 'watchexec --postpone --on-busy-update=queue "chezmoi apply"'
description = "Watch for and apply changes without forced, immediate reruns"
