[tools]
amp = "latest"
bun = "1.3"
claude = "latest"
codex = "latest"
elixir = "1.19"
erlang = "28.1"
flyctl = "latest"
gh = "latest"
"github:jclem/get" = "0.0.3"
go = "latest"
graphite = "latest"
just = "latest"
neovim = "latest"
node = "25.0"
npm = "11.6"
terraform = "latest"
uv = "0.9.3"
zig = "latest"
