[tools]
actionlint = "latest"
age = "1.3.1"
amp = "0.0.1771848350-g31e659"
bun = "1.3.9"
codex = "0.105.0"
elixir = "1.19.5-otp-28"
erlang = "28.3.2"
flyctl = "0.4.14"
fnox = "1.12.1"
gcloud = "557.0.0"
glow = "2.1.1"
go = "1.26.0"
graphite = "1.7.20"
just = "1.46.0"
lazygit = "latest"
neovim = "0.11.6"
node = "22.14.0"
npm = "10.9.2"
op = "2.32.1"
oxker = "latest"
rebar = "3.26.0"
ruby = "4.0.1"
rust = "1.93.1"
terraform = "1.14.5"
usage = "2.18.0"
uv = "0.10.4"
zig = "0.15.2"

[settings]
experimental = true
