[tools]
actionlint = "latest"
age = "1.3.1"
amp = "0.0.1771704097-g728b20"
bun = "1.3.9"
claude = "latest"
codex = "0.104.0"
elixir = "1.19.5-otp-28"
erlang = "28.3.2"
flyctl = "0.4.14"
fnox = "1.12.1"
gcloud = "557.0.0"
gh = "2.87.2"
glow = "2.1.1"
go = "1.26.0"
graphite = "1.7.20"
just = "1.46.0"
lazygit = "latest"
neovim = "0.11.6"
node = "25.6.1"
npm = "11.10.1"
op = "2.32.1"
rebar = "3.26.0"
ruby = "4.0.1"
rust = "1.93.1"
terraform = "1.14.5"
usage = "2.18.0"
uv = "0.10.4"
zig = "0.15.2"

[settings]
experimental = true
