[tools]
age = "latest"
amp = "latest"
bun = "latest"
codex = "latest"
elixir = "latest"
erlang = "latest"
flyctl = "latest"
fnox = "latest"
gcloud = "latest"
gh = "latest"
"github:jclem/get" = "0.0.3"
glow = "latest"
go = "latest"
graphite = "latest"
just = "latest"
neovim = "latest"
node = "25.6.1"
npm = "11.10.0"
op = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
zig = "latest"

[settings]
experimental = true
